
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.Connection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jafet
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        cargarAlumno();
        cargarProfesor();
        Licencia();
        cargarVehiculo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_alcomp = new javax.swing.JDialog();
        tp_entidad = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_al = new javax.swing.JTable();
        tp_al = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        tlic_al = new javax.swing.JTextField();
        nom_al = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pap_al = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jb_ag_al = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dir_al = new javax.swing.JTextField();
        tel_al = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dni_al = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sap_al = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        mtlic_al = new javax.swing.JTextField();
        mnom_al = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mpap_al = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jb_mod_al = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mdir_al = new javax.swing.JTextField();
        mtel_al = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mdni_al = new javax.swing.JTextField();
        mcosto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        msap_al = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jb_el_al = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jb_el_pr = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_pr = new javax.swing.JTable();
        tp_pr = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        nom_pr = new javax.swing.JTextField();
        pap_pr = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jb_ag_pr = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        dir_pr = new javax.swing.JTextField();
        tel_pr = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        dni_pr = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        sap_pr = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mnom_pr = new javax.swing.JTextField();
        mpap_pr = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jb_mod_pr = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        mdir_pr = new javax.swing.JTextField();
        mtel_pr = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        mdni_pr = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        msap_pr = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jb_el_ve = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_ve = new javax.swing.JTable();
        tp_ve = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        dni_ve = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jb_ag_ve = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        compra = new javax.swing.JTextField();
        tlic_ve = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        lujo = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        cilindrada = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tar = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        mcompra = new javax.swing.JTextField();
        mtlic_ve = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        mdni_ve = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        mmarca = new javax.swing.JTextField();
        mmatricula = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        mlujo = new javax.swing.JTextField();
        mmodelo = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        mcilindrada = new javax.swing.JTextField();
        jb_mod_ve = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jb_el_lic = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_lic = new javax.swing.JTable();
        tp_lic = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jb_ag_lic = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        tlic_lic = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jb_mod_lic = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        mtlic_lic = new javax.swing.JTextField();

        javax.swing.GroupLayout jd_alcompLayout = new javax.swing.GroupLayout(jd_alcomp.getContentPane());
        jd_alcomp.getContentPane().setLayout(jd_alcompLayout);
        jd_alcompLayout.setHorizontalGroup(
            jd_alcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jd_alcompLayout.setVerticalGroup(
            jd_alcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_al.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Primer apellido", "Segundo apellido", "Dirección", "Telefono", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_al);

        tp_al.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_alStateChanged(evt);
            }
        });

        jLabel10.setText("Tipo");

        jLabel11.setText("Segundo apellido");

        jb_ag_al.setText("Agregar");
        jb_ag_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ag_alActionPerformed(evt);
            }
        });

        jLabel12.setText("Costo");

        jLabel13.setText("Dirección");

        jLabel14.setText("DNI");

        jLabel9.setText("Primer apellido");

        jLabel15.setText("Nombre");

        jLabel16.setText("Telefono");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dir_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_ag_al))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dni_al)
                                    .addComponent(nom_al)
                                    .addComponent(sap_al)
                                    .addComponent(pap_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tel_al)
                                    .addComponent(costo)
                                    .addComponent(tlic_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dni_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tel_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nom_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlic_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pap_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sap_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dir_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ag_al))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_al.addTab("Agregar", jPanel3);

        jLabel17.setText("Tipo");

        jLabel18.setText("Segundo apellido");

        jb_mod_al.setText("Modificar");
        jb_mod_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mod_alActionPerformed(evt);
            }
        });

        jLabel19.setText("Costo");

        jLabel20.setText("Dirección");

        jLabel21.setText("DNI");

        jLabel22.setText("Primer apellido");

        jLabel23.setText("Nombre");

        jLabel24.setText("Telefono");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(mdir_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_mod_al))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdni_al)
                                    .addComponent(mnom_al)
                                    .addComponent(msap_al)
                                    .addComponent(mpap_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mtel_al)
                                    .addComponent(mcosto)
                                    .addComponent(mtlic_al, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(mdni_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(mtel_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(mnom_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mtlic_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(mcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpap_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(msap_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(mdir_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_mod_al))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_al.addTab("Modificar", jPanel4);

        jb_el_al.setText("Eliminar");
        jb_el_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_el_alActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tp_al, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jb_el_al)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tp_al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jb_el_al)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tp_entidad.addTab("Alumno", jPanel1);

        jb_el_pr.setText("Eliminar");
        jb_el_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_el_prActionPerformed(evt);
            }
        });

        tabla_pr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Primer apellido", "Segundo apellido", "Dirección", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_pr);

        tp_pr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_prStateChanged(evt);
            }
        });

        jLabel26.setText("Segundo apellido");

        jb_ag_pr.setText("Agregar");
        jb_ag_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ag_prActionPerformed(evt);
            }
        });

        jLabel28.setText("Dirección");

        jLabel29.setText("DNI");

        jLabel30.setText("Primer apellido");

        jLabel31.setText("Nombre");

        jLabel32.setText("Telefono");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(dir_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_ag_pr))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dni_pr)
                                    .addComponent(nom_pr)
                                    .addComponent(sap_pr)
                                    .addComponent(pap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(tel_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(dni_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(tel_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(nom_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(pap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(sap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(dir_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ag_pr))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_pr.addTab("Agregar", jPanel5);

        jLabel34.setText("Segundo apellido");

        jb_mod_pr.setText("Modificar");
        jb_mod_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mod_prActionPerformed(evt);
            }
        });

        jLabel36.setText("Dirección");

        jLabel37.setText("DNI");

        jLabel38.setText("Primer apellido");

        jLabel39.setText("Nombre");

        jLabel40.setText("Telefono");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel36))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(mdir_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_mod_pr))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdni_pr)
                                    .addComponent(mnom_pr)
                                    .addComponent(msap_pr)
                                    .addComponent(mpap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(mtel_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(mdni_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(mtel_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(mnom_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(mpap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(msap_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(mdir_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_mod_pr))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_pr.addTab("Modificar", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jb_el_pr)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tp_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jb_el_pr)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tp_entidad.addTab("Profesor", jPanel2);

        jb_el_ve.setText("Eliminar");
        jb_el_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_el_veActionPerformed(evt);
            }
        });

        tabla_ve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Marca", "Modelo", "Cilindrada", "Año de compra", "Tipo de licencia", "Tarifa", "DNI", "Tipo de lujo", "Licencia necesaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_ve.setToolTipText("");
        jScrollPane3.setViewportView(tabla_ve);

        tp_ve.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_veStateChanged(evt);
            }
        });

        jLabel25.setText("DNI");

        jLabel27.setText("Cilindrada");

        jb_ag_ve.setText("Agregar");
        jb_ag_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ag_veActionPerformed(evt);
            }
        });

        jLabel33.setText("Tipo de lujo");

        jLabel35.setText("Año de compra");

        jLabel41.setText("Matricula");

        jLabel42.setText("Modelo");

        jLabel43.setText("Marca");

        jLabel44.setText("Tipo de licencia");

        jLabel1.setText("Tarifa");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel35))
                                .addGap(46, 46, 46))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(74, 74, 74)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_ag_ve))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(matricula)
                                    .addComponent(marca)
                                    .addComponent(cilindrada)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tar)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tlic_ve)
                                        .addComponent(lujo)
                                        .addComponent(dni_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(tlic_ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni_ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(lujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ag_ve))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_ve.addTab("Agregar", jPanel8);

        jLabel53.setText("Tipo de licencia");

        jLabel54.setText("Tipo de coste");

        jLabel55.setText("Año de compra");

        jLabel56.setText("Matricula");

        jLabel57.setText("Modelo");

        jLabel58.setText("DNI");

        jLabel59.setText("Marca");

        jLabel60.setText("Cilindrada");

        jb_mod_ve.setText("Modificar");
        jb_mod_ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mod_veActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel55))
                                .addGap(46, 46, 46))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(74, 74, 74)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(mcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jb_mod_ve))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mmatricula)
                                    .addComponent(mmarca)
                                    .addComponent(mcilindrada)
                                    .addComponent(mmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mtlic_ve)
                                    .addComponent(mlujo)
                                    .addComponent(mdni_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(mmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(mtlic_ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(mmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mdni_ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(mlujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(mcilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(mcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_mod_ve))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_ve.addTab("Modificar", jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tp_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jb_el_ve)
                        .addGap(41, 41, 41))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tp_ve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jb_el_ve)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tp_entidad.addTab("Vehiculo", jPanel7);

        jb_el_lic.setText("Eliminar");
        jb_el_lic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_el_licActionPerformed(evt);
            }
        });

        tabla_lic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de licencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla_lic);

        tp_lic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_licStateChanged(evt);
            }
        });

        jb_ag_lic.setText("Agregar");
        jb_ag_lic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ag_licActionPerformed(evt);
            }
        });

        jLabel47.setText("Tipo de licencia");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(44, 44, 44)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jb_ag_lic))
                    .addComponent(tlic_lic, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(tlic_lic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(jb_ag_lic)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_lic.addTab("Agregar", jPanel11);

        jb_mod_lic.setText("Modificar");
        jb_mod_lic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mod_licActionPerformed(evt);
            }
        });

        jLabel61.setText("Tipo de licencia");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel61)
                .addGap(44, 44, 44)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jb_mod_lic))
                    .addComponent(mtlic_lic, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(mtlic_lic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(jb_mod_lic)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tp_lic.addTab("Modificar", jPanel12);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(tp_lic, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jb_el_lic)
                        .addGap(41, 41, 41))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tp_lic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jb_el_lic)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tp_entidad.addTab("Licencia", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_entidad)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_entidad)
                .addContainerGap())
        );

        tp_entidad.getAccessibleContext().setAccessibleName("Alumno");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tp_alStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_alStateChanged
        // TODO add your handling code here:

        if (tp_al.getSelectedIndex() == 1) {
            if (tabla_al.getSelectedRow() >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabla_al.getModel();
                int fila = tabla_al.getSelectedRow();
                mdni_al.setText(model.getValueAt(fila, 0).toString());
                mnom_al.setText(model.getValueAt(fila, 1).toString());
                mpap_al.setText(model.getValueAt(fila, 2).toString());
                msap_al.setText(model.getValueAt(fila, 3).toString());
                mdir_al.setText(model.getValueAt(fila, 4).toString());
                mtel_al.setText(model.getValueAt(fila, 5).toString());
                mtlic_al.setText(model.getValueAt(fila, 6).toString());
                mcosto.setText(model.getValueAt(fila, 7).toString());
            } else {
                tp_al.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "No hay fila seleccionada");

            }
        }

    }//GEN-LAST:event_tp_alStateChanged

    private void jb_ag_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ag_alActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_al.getModel();
        /*String[] row = {dni_al.getText(), nom_al.getText(), pap_al.getText(), sap_al.getText(), dir_al.getText(), tel_al.getText(), tlic_al.getText(), costo.getText()};
        model.addRow(row);*/
        guardarAlumno();
        limpiarAl();
        cargarAlumno();
        
    }//GEN-LAST:event_jb_ag_alActionPerformed

    private void jb_mod_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mod_alActionPerformed
        // TODO add your handling code here:
        // if (tabla_al.getSelectedRow() >)
        DefaultTableModel model = (DefaultTableModel) tabla_al.getModel();
        int fila = tabla_al.getSelectedRow();
        model.setValueAt(mdni_al.getText(), fila, 0);
        model.setValueAt(mnom_al.getText(), fila, 1);
        model.setValueAt(mpap_al.getText(), fila, 2);
        model.setValueAt(msap_al.getText(), fila, 3);
        model.setValueAt(mdir_al.getText(), fila, 4);
        model.setValueAt(mtel_al.getText(), fila, 5);
        model.setValueAt(mtlic_al.getText(), fila, 6);
        model.setValueAt(mcosto.getText(), fila, 7);
    }//GEN-LAST:event_jb_mod_alActionPerformed

    private void jb_el_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_el_alActionPerformed
        // TODO add your handling code here:
        if (tabla_al.getSelectedRow() >= 0) {
            int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar la fila seleccionada", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tabla_al.getModel();
                model.removeRow(tabla_al.getSelectedRow());
                tp_al.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jb_el_alActionPerformed

    private void jb_el_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_el_prActionPerformed
        // TODO add your handling code here:
        if (tabla_pr.getSelectedRow() >= 0) {
            int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar la fila seleccionada", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tabla_pr.getModel();
                model.removeRow(tabla_pr.getSelectedRow());
                tp_pr.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jb_el_prActionPerformed

    private void jb_ag_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ag_prActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_pr.getModel();
        guardarProf();
        limpiarPr();
        cargarProfesor();
        // Assuming tabla_pr is your new table model
        
    }//GEN-LAST:event_jb_ag_prActionPerformed

    private void jb_mod_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mod_prActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_pr.getModel();
        int fila = tabla_pr.getSelectedRow();
        model.setValueAt(mdni_pr.getText(), fila, 0);
        model.setValueAt(mnom_pr.getText(), fila, 1);
        model.setValueAt(mpap_pr.getText(), fila, 2);
        model.setValueAt(msap_pr.getText(), fila, 3);
        model.setValueAt(mdir_pr.getText(), fila, 4);
        model.setValueAt(mtel_pr.getText(), fila, 5);
    }//GEN-LAST:event_jb_mod_prActionPerformed

    private void tp_prStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_prStateChanged
        // TODO add your handling code here:
        if (tp_pr.getSelectedIndex() == 1) {
            if (tabla_pr.getSelectedRow() >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabla_pr.getModel();
                int fila = tabla_pr.getSelectedRow();
                mdni_pr.setText(model.getValueAt(fila, 0).toString());
                mnom_pr.setText(model.getValueAt(fila, 1).toString());
                mpap_pr.setText(model.getValueAt(fila, 2).toString());
                msap_pr.setText(model.getValueAt(fila, 3).toString());
                mdir_pr.setText(model.getValueAt(fila, 4).toString());
                mtel_pr.setText(model.getValueAt(fila, 5).toString());
            } else {
                tp_pr.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "No hay fila seleccionada");

            }
        }
    }//GEN-LAST:event_tp_prStateChanged

    private void jb_el_veActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_el_veActionPerformed
        // TODO add your handling code here:
        if (tabla_ve.getSelectedRow() >= 0) {
            int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar la fila seleccionada", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tabla_ve.getModel();
                model.removeRow(tabla_ve.getSelectedRow());
                tp_ve.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jb_el_veActionPerformed

    private void jb_ag_veActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ag_veActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_ve.getModel(); // Assuming tabla_ve is your new table model
        String[] row = {matricula.getText(), marca.getText(), modelo.getText(), cilindrada.getText(), compra.getText(), tlic_ve.getText(), dni_ve.getText(), lujo.getText()};
        model.addRow(row);
        guardarVehiculo();
        limpiarVe();
        cargarVehiculo();
    }//GEN-LAST:event_jb_ag_veActionPerformed

    private void tp_veStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_veStateChanged
        // TODO add your handling code here:
        if (tp_ve.getSelectedIndex() == 1) {
            if (tabla_ve.getSelectedRow() >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabla_ve.getModel();
                int fila = tabla_ve.getSelectedRow();
                mmatricula.setText(model.getValueAt(fila, 0).toString());
                mmarca.setText(model.getValueAt(fila, 1).toString());
                mmodelo.setText(model.getValueAt(fila, 2).toString());
                mcilindrada.setText(model.getValueAt(fila, 3).toString());
                mcompra.setText(model.getValueAt(fila, 4).toString());
                mtlic_ve.setText(model.getValueAt(fila, 5).toString());
                mdni_ve.setText(model.getValueAt(fila, 6).toString());
                mlujo.setText(model.getValueAt(fila, 7).toString());
            } else {
                tp_ve.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "No hay fila seleccionada");
            }
        }

    }//GEN-LAST:event_tp_veStateChanged

    private void jb_mod_veActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mod_veActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_ve.getModel();
        int fila = tabla_ve.getSelectedRow();
        model.setValueAt(mmatricula.getText(), fila, 0);
        model.setValueAt(mmarca.getText(), fila, 1);
        model.setValueAt(mmodelo.getText(), fila, 2);
        model.setValueAt(mcilindrada.getText(), fila, 3);
        model.setValueAt(mcompra.getText(), fila, 4);
        model.setValueAt(mtlic_ve.getText(), fila, 5);
        model.setValueAt(mdni_ve.getText(), fila, 6);
        model.setValueAt(mlujo.getText(), fila, 7);

    }//GEN-LAST:event_jb_mod_veActionPerformed

    private void jb_el_licActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_el_licActionPerformed
        // TODO add your handling code here:
        if (tabla_lic.getSelectedRow() >= 0) {
            int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar la fila seleccionada", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tabla_lic.getModel();
                model.removeRow(tabla_lic.getSelectedRow());
                tp_lic.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jb_el_licActionPerformed

    private void jb_ag_licActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ag_licActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_lic.getModel(); // Assuming tabla_ve is your new table model
        String[] row = {tlic_lic.getText()};
        model.addRow(row);
        guardarLic();
        limpiarLic();
        Licencia();
    }//GEN-LAST:event_jb_ag_licActionPerformed

    private void jb_mod_licActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mod_licActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla_lic.getModel();
        int fila = tabla_lic.getSelectedRow();
        model.setValueAt(mtlic_lic.getText(), fila, 0);
    }//GEN-LAST:event_jb_mod_licActionPerformed

    private void tp_licStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_licStateChanged
        // TODO add your handling code here:
        if (tp_lic.getSelectedIndex() == 1) {
            if (tabla_lic.getSelectedRow() >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabla_lic.getModel();
                int fila = tabla_lic.getSelectedRow();
                mtlic_lic.setText(model.getValueAt(fila, 0).toString());

            } else {
                tp_lic.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "No hay fila seleccionada");
            }
        }
    }//GEN-LAST:event_tp_licStateChanged

    /**
     * @param args the command line arguments
     */
    private void cargarAlumno() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla_al.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("select dni_al, nombre, apellido_1, apellido_2, "
                    + "direccion, telefono, tipo_lic, coste_et from Alumno");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    
    
    private void cargarProfesor() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla_pr.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("select dni_prof, nombre, apellido_1, apellido_2, "
                    + "direccion, telefono from Profesor");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    private void cargarVehiculo() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla_ve.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("select matricula, marca, modelo, cilindrada, "
                    + "anio_compra, tipo_lic,tarifa, dni_prof, tipo_lujo, licencia_necesaria from Vehiculo");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    private void Licencia() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla_lic.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("select tipo_lic from Licencia");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    private void limpiarAl() {
        dni_al.setText("");
        nom_al.setText("");
        pap_al.setText("");
        sap_al.setText("");
        dir_al.setText("");
        tel_al.setText("");
        tlic_al.setText("");
        
    }

    private void limpiarPr() {
        dni_pr.setText("");
        nom_pr.setText("");
        pap_pr.setText("");
        sap_pr.setText("");
        dir_al.setText("");
        tel_pr.setText("");
    }

    private void limpiarVe() {
        matricula.setText("");
        marca.setText("");
        modelo.setText("");
        cilindrada.setText("");
        compra.setText("");
        tlic_ve.setText("");
        dni_ve.setText("");
        lujo.setText("");
    }

    private void limpiarLic() {
        tlic_lic.setText("");
    }

    private void guardarAlumno() {
        PreparedStatement ps;
        ResultSet rs;
        String dni = dni_al.getText();
        String nombre = nom_al.getText();
        String pap = pap_al.getText();
        String sap = sap_al.getText();
        String dir = dir_al.getText();
        int tel = Integer.parseInt(tel_al.getText());
        String tipo = tlic_al.getText();
        
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("insert into Alumno (dni_al, nombre, apellido_1, apellido_2, " + "direccion, telefono, tipo_lic) values (?,?,?,?,?,?,?)");
            ps.setString(1, dni);
            ps.setString(2, nombre);
            ps.setString(3, pap);
            ps.setString(4, sap);
            ps.setString(5, dir);
            ps.setInt(6, tel);
            ps.setString(7, tipo);
            ps.executeUpdate();

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    private void guardarProf() {
       
        PreparedStatement ps;
        ResultSet rs;
        String dni = dni_pr.getText();
        String nombre = nom_pr.getText();
        String pap = pap_pr.getText();
        String sap = sap_pr.getText();
        String dir = dir_pr.getText();
        int tel = Integer.parseInt(tel_pr.getText());
        String tipo = tlic_al.getText();
        
        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("insert into Profesor (dni_prof, nombre, apellido_1, apellido_2, " + "direccion, telefono) values (?,?,?,?,?,?)");
            ps.setString(1, dni);
            ps.setString(2, nombre);
            ps.setString(3, pap);
            ps.setString(4, sap);
            ps.setString(5, dir);
            ps.setInt(6, tel);
            ps.executeUpdate();

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    
    private void guardarVehiculo() {
    PreparedStatement ps;
    ResultSet rs;
    
    String mat = matricula.getText();
    String marc = marca.getText();
    String model = modelo.getText();
    int cilind = Integer.parseInt(cilindrada.getText());
    String anioCompra = compra.getText();
    int tarifa = Integer.parseInt(tar.getText());
    int dniProfesor = Integer.parseInt(dni_ve.getText());
    String tipoLujo = lujo.getText();
    String licenciaNecesaria = tlic_ve.getText();
    
    try {
        Connection con = Conexion.getConnection();
        ps = con.prepareStatement("INSERT INTO Vehiculo (matricula, marca, modelo, cilindrada, anio_compra, tarifa, tipo_lic, dni_prof, tipo_lujo) VALUES (?,?,?,?,?,?,?,?,?)");
        ps.setString(1, mat);
        ps.setString(2, marc);
        ps.setString(3, model);
        ps.setInt(4, cilind);
        ps.setString(5, anioCompra);
        ps.setInt(6, tarifa);
        ps.setString(7, licenciaNecesaria);
        ps.setInt(8, dniProfesor);
        ps.setString(9, tipoLujo);
        
        ps.executeUpdate();

    } catch (SQLException ex) {
        System.out.println(ex.toString());
    }
}
    
    private void guardarLic() {
    PreparedStatement ps;
    ResultSet rs;
    
    String lic = tlic_lic.getText();
    
    try {
        Connection con = Conexion.getConnection();
        ps = con.prepareStatement("INSERT INTO Licencia (tipo_lic) VALUES (?)");
        ps.setString(1, lic);
        ps.executeUpdate();

    } catch (SQLException ex) {
        System.out.println(ex.toString());
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cilindrada;
    private javax.swing.JTextField compra;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField dir_al;
    private javax.swing.JTextField dir_pr;
    private javax.swing.JTextField dni_al;
    private javax.swing.JTextField dni_pr;
    private javax.swing.JTextField dni_ve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_ag_al;
    private javax.swing.JButton jb_ag_lic;
    private javax.swing.JButton jb_ag_pr;
    private javax.swing.JButton jb_ag_ve;
    private javax.swing.JButton jb_el_al;
    private javax.swing.JButton jb_el_lic;
    private javax.swing.JButton jb_el_pr;
    private javax.swing.JButton jb_el_ve;
    private javax.swing.JButton jb_mod_al;
    private javax.swing.JButton jb_mod_lic;
    private javax.swing.JButton jb_mod_pr;
    private javax.swing.JButton jb_mod_ve;
    private javax.swing.JDialog jd_alcomp;
    private javax.swing.JTextField lujo;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField mcilindrada;
    private javax.swing.JTextField mcompra;
    private javax.swing.JTextField mcosto;
    private javax.swing.JTextField mdir_al;
    private javax.swing.JTextField mdir_pr;
    private javax.swing.JTextField mdni_al;
    private javax.swing.JTextField mdni_pr;
    private javax.swing.JTextField mdni_ve;
    private javax.swing.JTextField mlujo;
    private javax.swing.JTextField mmarca;
    private javax.swing.JTextField mmatricula;
    private javax.swing.JTextField mmodelo;
    private javax.swing.JTextField mnom_al;
    private javax.swing.JTextField mnom_pr;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField mpap_al;
    private javax.swing.JTextField mpap_pr;
    private javax.swing.JTextField msap_al;
    private javax.swing.JTextField msap_pr;
    private javax.swing.JTextField mtel_al;
    private javax.swing.JTextField mtel_pr;
    private javax.swing.JTextField mtlic_al;
    private javax.swing.JTextField mtlic_lic;
    private javax.swing.JTextField mtlic_ve;
    private javax.swing.JTextField nom_al;
    private javax.swing.JTextField nom_pr;
    private javax.swing.JTextField pap_al;
    private javax.swing.JTextField pap_pr;
    private javax.swing.JTextField sap_al;
    private javax.swing.JTextField sap_pr;
    private javax.swing.JTable tabla_al;
    private javax.swing.JTable tabla_lic;
    private javax.swing.JTable tabla_pr;
    private javax.swing.JTable tabla_ve;
    private javax.swing.JTextField tar;
    private javax.swing.JTextField tel_al;
    private javax.swing.JTextField tel_pr;
    private javax.swing.JTextField tlic_al;
    private javax.swing.JTextField tlic_lic;
    private javax.swing.JTextField tlic_ve;
    private javax.swing.JTabbedPane tp_al;
    private javax.swing.JTabbedPane tp_entidad;
    private javax.swing.JTabbedPane tp_lic;
    private javax.swing.JTabbedPane tp_pr;
    private javax.swing.JTabbedPane tp_ve;
    // End of variables declaration//GEN-END:variables
}
